image.c: Fix build warning on macOS
When building tools on macOS today we see:
In file included from tools/common/image.c:1:
./tools/../common/image.c:501:10: error: implicit declaration of function 'ulz4fn' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        ret = ulz4fn(image_buf, image_len, load_buf, &size);
                              ^
as we get the system lz4.h rather than our own.  Rework our include list
so that target builds get <lz4.h> and tool builds get "lz4.h" to specify
local rather than system includes.

Signed-off-by: Tom Rini <trini@konsulko.com>