efi_loader: fix efi_dp_from_eth
When compiling the sandbox with CONFIG_LTO=n, CONFIG_NET=n an error is
reported:

    /usr/bin/ld: lib/efi_loader/efi_device_path.o:
    in function `efi_dp_from_eth':
    lib/efi_loader/efi_device_path.c:985:(.text+0xcf4):
    undefined reference to `eth_get_dev'

Add a missing configuration check.

As the function is exported __maybe_unused can be removed.

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
Reviewed-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
Reviewed-by: Simon Glass <sjg@chromium.org>